baseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "zh-tw"
title = "Alice's Hugo Site"
theme = "tranquilpeak"
# googleAnalytics = "UA-123-45"
paginate = 7
canonifyurls = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"


[author]
  name = "Alice Lee"
  bio = "Super bio with markdown support **COOL**"
  job = "Front End Enginner"
  location = "Taiwan"
  picture = "https://i.imgur.com/1Kff7NI.jpg"
  twitter = "alicexdcw"

# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/post"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"
[[menu.main]]
  weight = 6
  identifier = "活動頁"
  name = "Event"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-event\"></i>"
  url = "/page"
[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/kakawait"
#[[menu.links]]
 # weight = 2
 # identifier = "stackoverflow"
 # name = "Stack Overflow"
 # pre = "<i class=\"sidebar-button-icon fa fa-lg fa-stack-overflow\"></i>"
 # url = "https://stackoverflow.com/users/636472/kakawait"



  [params]
  # Global keywords configuration. Following keywords will be add to every pages
  # keywords = ["development", "next-gen"]

  # Syntax highlighter, possible choice between: "highlight.js" (recommanded) and "prism.js" (experimental)
  # You can comment it to disable syntax highlighting
  syntaxHighlighter = "highlight.js"

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = true

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo".
  # If false it will flat categories.
  hierarchicalCategories = true

  description = "Alice's Blog"
  sidebarBehavior = 2 #sidebar的模式

  #Image 
  coverImage = "https://picsum.photos/id/10/2500/1667"
  imageGallery = true
  thumbnailImage = true #文章縮圖 
  thumbnailImagePosition = "left" #首頁文章列表中，縮圖與標題的相對位置
  autoThumbnailImage = true

  #換行、目錄
[markup]
defaultMarkdownHandler = "blackfriday"
[blackfriday]
extensions = ["hardLineBreak"]

  # Sharing options
  # Comment and uncomment to enable or disable sharing options
  # If you wanna add a sharing option, read user documentation :
  # Tranquilpeak configuration > Theme configuration > sharing-options
  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-official"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"

  [[params.sharingOptions]]
    name = "Twitter"
    icon = "fa-twitter"
    url = "https://twitter.com/intent/tweet?text=%s"

  [[params.sharingOptions]]
    name = "Google+"
    icon = "fa-google-plus"
    url = "https://plus.google.com/share?url=%s"

  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"

  # Customize link of author avatar in sidebar
  # [params.sidebar.profile]
  #   url = "/#about"

  # Customize copyright value "© 2017 <CUSTOMIZATION>. All Rights Reserved"
  # [params.footer]
  #   copyright = "<a href=\"https://github.com/kakawait\">kakawait</a>"


